export default PegaUidInteger;
declare function PegaUidInteger(props: any): JSX.Element;
declare namespace PegaUidInteger {
    namespace defaultProps {
        const value: string;
        const defaultValue: null;
        const placeholder: string;
        const validatemessage: string;
        const helperText: string;
        const hideLabel: boolean;
        const disabled: boolean;
        const readOnly: boolean;
        const required: boolean;
        const testId: null;
        const showGroupSeparators: boolean;
        const displayMode: null;
        const displayAs: string;
        const showInput: boolean;
        const min: number;
        const max: number;
        const step: number;
        const showTicks: boolean;
        const additionalProps: {};
        const variant: string;
        const decimalPrecision: null;
        const currencyISOCode: string;
        const isoCodeSelection: string;
        const formatter: string;
        const negative: string;
        const notation: string;
        const currencyDisplay: string;
        const currencyDecimalPrecision: string;
        const isTableFormatter: boolean;
        const hasSuggestions: boolean;
    }
    namespace propTypes {
        const value_1: PropTypes.Requireable<string>;
        export { value_1 as value };
        const defaultValue_1: PropTypes.Requireable<number>;
        export { defaultValue_1 as defaultValue };
        const placeholder_1: PropTypes.Requireable<string>;
        export { placeholder_1 as placeholder };
        export const label: PropTypes.Validator<string>;
        const hideLabel_1: PropTypes.Requireable<boolean>;
        export { hideLabel_1 as hideLabel };
        export const getPConnect: PropTypes.Validator<(...args: any[]) => any>;
        const validatemessage_1: PropTypes.Requireable<string>;
        export { validatemessage_1 as validatemessage };
        const helperText_1: PropTypes.Requireable<string>;
        export { helperText_1 as helperText };
        const disabled_1: PropTypes.Requireable<NonNullable<string | boolean | null | undefined>>;
        export { disabled_1 as disabled };
        const readOnly_1: PropTypes.Requireable<NonNullable<string | boolean | null | undefined>>;
        export { readOnly_1 as readOnly };
        const required_1: PropTypes.Requireable<NonNullable<string | boolean | null | undefined>>;
        export { required_1 as required };
        const testId_1: PropTypes.Requireable<string>;
        export { testId_1 as testId };
        const showGroupSeparators_1: PropTypes.Requireable<boolean>;
        export { showGroupSeparators_1 as showGroupSeparators };
        const displayMode_1: PropTypes.Requireable<string>;
        export { displayMode_1 as displayMode };
        const displayAs_1: PropTypes.Requireable<string>;
        export { displayAs_1 as displayAs };
        const showInput_1: PropTypes.Requireable<boolean>;
        export { showInput_1 as showInput };
        const min_1: PropTypes.Requireable<number>;
        export { min_1 as min };
        const max_1: PropTypes.Requireable<number>;
        export { max_1 as max };
        const step_1: PropTypes.Requireable<number>;
        export { step_1 as step };
        const showTicks_1: PropTypes.Requireable<boolean>;
        export { showTicks_1 as showTicks };
        const additionalProps_1: PropTypes.Requireable<{
            [x: string]: any;
        }>;
        export { additionalProps_1 as additionalProps };
        const variant_1: PropTypes.Requireable<string>;
        export { variant_1 as variant };
        const decimalPrecision_1: PropTypes.Requireable<number>;
        export { decimalPrecision_1 as decimalPrecision };
        const currencyISOCode_1: PropTypes.Requireable<string>;
        export { currencyISOCode_1 as currencyISOCode };
        const isoCodeSelection_1: PropTypes.Requireable<string>;
        export { isoCodeSelection_1 as isoCodeSelection };
        const formatter_1: PropTypes.Requireable<string>;
        export { formatter_1 as formatter };
        const negative_1: PropTypes.Requireable<string>;
        export { negative_1 as negative };
        const notation_1: PropTypes.Requireable<string>;
        export { notation_1 as notation };
        const currencyDisplay_1: PropTypes.Requireable<string>;
        export { currencyDisplay_1 as currencyDisplay };
        const currencyDecimalPrecision_1: PropTypes.Requireable<string>;
        export { currencyDecimalPrecision_1 as currencyDecimalPrecision };
        const isTableFormatter_1: PropTypes.Requireable<boolean>;
        export { isTableFormatter_1 as isTableFormatter };
        const hasSuggestions_1: PropTypes.Requireable<boolean>;
        export { hasSuggestions_1 as hasSuggestions };
    }
}
import PropTypes from "prop-types";
//# sourceMappingURL=index.d.ts.map